# Generated by Django 3.2.5 on 2021-08-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_auto_20210805_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='addess',
            new_name='address',
        ),
    ]
